apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-dotnet
  template:
    metadata:
      labels:
        app: api-dotnet
    spec:
      containers:
        - name: api-dotnet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
